services:
  bentopdf:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SIMPLE_MODE: false # false for default mode, true for simple mode
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN:-}
    container_name: bentopdf
    ports:
      - '8080:8080'
    restart: unless-stopped
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
