name: Deploy to Production

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy_production:
    uses: ./.github/workflows/deploy-cloudflare.yml
    secrets:
      api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    with:
      branch: ${{ github.event.release.tag_name }}
      ref: ${{ github.event.release.tag_name }}
      update_production_branch: true
